name: geoponto
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  intl: ^0.19.0
  geolocator: ^12.0.0
  geolocator_linux: ^0.2.3
  flutter_map: ^8.2.2
  geocoding: ^4.0.0
  month_picker_dialog: ^3.0.0
  shared_preferences: ^2.2.3
  camera: ^0.11.0+2
  tflite_flutter: ^0.12.1
  latlong2: ^0.9.1
  image: ^4.3.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/geoponto_extractor.tflite